import { useEffect, useMemo, useRef, useState } from 'react'
import { Check, CheckCircle2, ChevronRight, Clock3, Crown, LoaderCircle, PartyPopper, RotateCw, Send, Trophy, WifiOff, XCircle } from 'lucide-react'
import { Link, Navigate, useParams } from '../lib/router'
import { api } from '../lib/api'
import { createId } from '../lib/id'
import { useGameStore } from '../store/game'
import type { Question, Snapshot } from '../types'
import { Badge, Button, Card, ConnectionPill, Logo, formatTime } from '../components/ui'
import { CountdownNumber, Timer } from '../components/Timer'

export function GuestPage() {
  const code = useParams().code!.toUpperCase(); const token = localStorage.getItem(`device_${code}`); const participantId = localStorage.getItem(`participant_${code}`)
  const snapshot = useGameStore(s => s.snapshot); const connection = useGameStore(s => s.connection); const latency = useGameStore(s => s.latency)
  const [selected, setSelected] = useState<unknown>(null); const [submitted, setSubmitted] = useState(false); const [sending, setSending] = useState(false); const [error, setError] = useState(''); const questionId = snapshot?.question?.id
  useEffect(() => { if (token) { useGameStore.getState().connect(code, token); void api.ready(code, { device_token: token, latency_ms: latency, media_ready: true, sound_ready: true }).catch(() => undefined) } return () => useGameStore.getState().disconnect() }, [code, token])
  useEffect(() => { setSelected(null); setSubmitted(false); setError('') }, [questionId])
  useEffect(() => { if (snapshot?.session.status === 'reveal' && snapshot.event.content_mode !== 'survey' && navigator.vibrate) navigator.vibrate(snapshot.private_result?.is_correct ? [80, 60, 80] : 80) }, [snapshot?.session.status])
  if (!token) return <Navigate to={`/join/${code}`} replace />
  if (!snapshot) return <div className="guest-shell"><GuestHeader connection={connection} latency={latency} /><div className="center-panel"><LoaderCircle className="spin" size={30} /><p>Возвращаем вас в комнату…</p></div></div>
  const self = snapshot.participants.find(p => p.id === participantId); const team = snapshot.teams.find(t => t.id === self?.team_id); const captain = snapshot.event.game_mode !== 'team' || team?.captain_participant_id === self?.id
  const submit = async (answer = selected) => { if (sending || submitted) return; setSending(true); setError(''); try { await api.answer(code, { device_token: token, request_id: createId(), answer }); setSubmitted(true); setSelected(answer); await useGameStore.getState().refresh(code, token) } catch (err) { setError(err instanceof Error ? err.message : 'Ответ не отправлен') } finally { setSending(false) } }
  const heroSubmit = async (answer = selected) => { setSending(true); try { await api.heroChoice(code, { device_token: token, request_id: createId(), answer }); setSubmitted(true) } catch (err) { setError(err instanceof Error ? err.message : 'Выбор не отправлен') } finally { setSending(false) } }
  const status = snapshot.session.status; const isHeroChoice = self?.role === 'hero' && snapshot.question?.type === 'hero_choice'; const eligible = self?.eligible !== false
  return <main className="guest-shell" style={{ '--accent': snapshot.event.theme.accent } as React.CSSProperties}><GuestHeader connection={connection} latency={latency} name={self?.name} avatar={self?.avatar} />
    <section className="guest-content">
      {connection === 'offline' && <div className="offline-overlay"><WifiOff /><h2>Связь потеряна</h2><p>Не закрывайте страницу — возвращаем вас в игру.</p><LoaderCircle className="spin" /></div>}
      {status === 'lobby' && <Waiting snapshot={snapshot} selfName={self?.name} avatar={self?.avatar} />}
      {!eligible && status !== 'finished' && <Card className="state-card"><span className="state-icon">⌛</span><Badge tone="warning">Поздний вход</Badge><h2>Вы в игре!</h2><p>Текущий вопрос уже начался. Вы сможете отвечать со следующего — так будет честно для всех.</p><strong>Сейчас вопрос {snapshot.session.current_question_index + 1} из {snapshot.session.question_count}</strong></Card>}
      {eligible && status === 'countdown' && <Card className="state-card countdown-card"><span className="round-chip">{snapshot.question?.round_title}</span><CountdownNumber className="countdown-number" deadline={snapshot.session.deadline_at} total={snapshot.event.auto_advance_seconds} serverTime={snapshot.server_time} /><h2>Приготовьтесь!</h2><p>{snapshot.session.deadline_at ? `Вопрос ${snapshot.session.current_question_index + 1} начнётся автоматически` : 'Организатор скоро откроет вопрос'}</p></Card>}
      {eligible && status === 'answering' && (!isHeroChoice ? <AnswerCard question={snapshot.question!} selected={selected} setSelected={setSelected} submitted={submitted} sending={sending} captain={captain} deadline={snapshot.session.deadline_at} serverTime={snapshot.server_time} error={error} onSubmit={() => void submit()} onSkip={() => void submit(null)} /> : <Card className="state-card"><span className="state-icon">🤫</span><Badge tone="accent">Ваш секретный выбор</Badge><h2>Сначала выбирают гости</h2><p>Как только ответы закроются, здесь появятся варианты. Ваш выбор станет правильным.</p></Card>)}
      {eligible && ['locked', 'review'].includes(status) && isHeroChoice && !submitted && <HeroChoice question={snapshot.question!} selected={selected} setSelected={setSelected} sending={sending} error={error} onSubmit={() => void heroSubmit()} />}
      {eligible && ['locked', 'review'].includes(status) && (!isHeroChoice || submitted) && <Card className="state-card"><span className="state-icon">🔐</span><Badge tone="neutral">Ответы закрыты</Badge><h2>{submitted ? 'Ваш ответ принят' : 'Время вышло'}</h2><p>Организатор готовит раскрытие. Совсем скоро узнаем правильный ответ.</p></Card>}
      {eligible && status === 'reveal' && <PrivateResult snapshot={snapshot} />}
      {status === 'paused' && <Card className="state-card"><span className="state-icon">Ⅱ</span><Badge tone="warning">Пауза</Badge><h2>Небольшая остановка</h2><p>Таймер заморожен. Организатор скоро продолжит игру.</p></Card>}
      {status === 'cancelled' && <Card className="state-card"><span className="state-icon">↩</span><Badge tone="warning">Вопрос отменён</Badge><h2>Не считаем этот ответ</h2><p>Результат вопроса удалён. Ждём следующий.</p></Card>}
      {status === 'finished' && <><PersonalFinal snapshot={snapshot} /><Card className="guest-account-invite"><Crown /><div><Badge tone="accent">Необязательно</Badge><h3>Сохранить результат?</h3><p>Создайте аккаунт по номеру телефона — мы предложим привязать все игры с этого устройства.</p></div><Link className="button button-secondary" to="/account?register=1">Сохранить мои игры</Link></Card></>}
    </section><footer className="guest-footer"><span>{snapshot.event.title}</span><span>·</span><span>{snapshot.session.current_question_index + 1}/{snapshot.session.question_count}</span></footer></main>
}

function GuestHeader({ connection, latency, name, avatar }: { connection: string; latency: number | null; name?: string; avatar?: string }) { return <header className="guest-header"><Logo compact /><ConnectionPill state={connection} latency={latency} />{name && <div className="guest-profile"><span>{avatar}</span><b>{name}</b></div>}</header> }

function Waiting({ snapshot, selfName, avatar }: { snapshot: Snapshot; selfName?: string; avatar?: string }) { const ready = snapshot.participants.filter(p => p.ready).length; return <Card className="waiting-card"><div className="waiting-visual"><span>{avatar}</span><i /><i /><i /></div><Badge tone="success"><Check size={14} /> Вы в комнате</Badge><h1>Всё готово, {selfName}!</h1><p>Ждём остальных игроков и команду организатора.</p><div className="waiting-stats"><div><b>{ready}</b><span>готовы играть</span></div><div><b>{snapshot.session.question_count}</b><span>вопросов впереди</span></div></div><small>Телефон можно не выключать. Экран обновится сам.</small></Card> }

function AnswerCard({ question, selected, setSelected, submitted, sending, captain, deadline, serverTime, error, onSubmit, onSkip }: { question: Question; selected: unknown; setSelected: (x: unknown) => void; submitted: boolean; sending: boolean; captain: boolean; deadline?: string | null; serverTime?: string | null; error: string; onSubmit: () => void; onSkip: () => void }) {
  if (!captain) return <Card className="state-card"><span className="state-icon">👑</span><Badge tone="accent">Командная игра</Badge><h2>Решайте вместе</h2><p>Окончательный ответ отправляет капитан вашей команды.</p></Card>
  const multi = question.type === 'multiple'; const chosen = new Set(Array.isArray(selected) ? selected as string[] : [])
  const choose = (id: string) => { if (submitted) return; if (multi) { chosen.has(id) ? chosen.delete(id) : chosen.add(id); setSelected([...chosen]) } else setSelected(id) }
  return <Card className="answer-card"><div className="answer-top"><div><span>{question.round_title}</span><small>{question.type === 'multiple' ? 'Выберите все подходящие' : 'Выберите ответ'}</small></div><Timer deadline={deadline} total={question.time_limit_seconds} serverTime={serverTime} /></div><h1>{question.text}</h1>{question.media_url && (question.media_type === 'audio' ? <audio className="question-audio" controls src={question.media_url} /> : <img className="question-image" src={question.media_url} alt="Иллюстрация к вопросу" />)}{question.options.length > 0 && <div className="guest-options">{question.options.map((option, index) => { const active = multi ? chosen.has(option.id) : selected === option.id; return <button key={option.id} className={active ? 'selected' : ''} disabled={submitted} onClick={() => choose(option.id)}><i>{active ? <Check /> : String.fromCharCode(65 + index)}</i><span>{option.text}</span></button> })}</div>}{['text', 'number', 'closest'].includes(question.type) && <input className="free-answer" type={question.type === 'text' ? 'text' : 'number'} inputMode={question.type === 'text' ? 'text' : 'numeric'} value={String(selected ?? '')} onChange={e => setSelected(e.target.value)} placeholder={question.type === 'text' ? 'Ваш короткий ответ' : 'Введите число'} disabled={submitted} />}{error && <p className="form-error">{error}</p>}{submitted ? <div className="accepted-bar"><CheckCircle2 /><span><b>Ответ принят</b><small>Изменить его уже нельзя</small></span></div> : <div className="answer-actions"><Button onClick={onSubmit} disabled={selected === null || selected === '' || sending}>{sending ? <LoaderCircle className="spin" /> : <Send />} Ответить</Button><Button variant="ghost" onClick={onSkip} disabled={sending}>Пропустить</Button></div>}</Card>
}

function HeroChoice({ question, selected, setSelected, sending, error, onSubmit }: { question: Question; selected: unknown; setSelected: (x: unknown) => void; sending: boolean; error: string; onSubmit: () => void }) { return <Card className="answer-card hero-choice"><Badge tone="accent"><Crown size={14} /> Только для героя</Badge><h1>Гости уже сделали выбор</h1><p>Теперь выберите, что действительно выбрали бы вы.</p><div className="guest-options">{question.options.map((option, index) => <button key={option.id} className={selected === option.id ? 'selected' : ''} onClick={() => setSelected(option.id)}><i>{selected === option.id ? <Check /> : String.fromCharCode(65 + index)}</i><span>{option.text}</span></button>)}</div>{error && <p className="form-error">{error}</p>}<Button onClick={onSubmit} disabled={!selected || sending}>{sending ? <LoaderCircle className="spin" /> : <Crown />} Это мой выбор</Button></Card> }

function PrivateResult({ snapshot }: { snapshot: Snapshot }) {
  const result = snapshot.private_result
  if (snapshot.event.content_mode === 'survey') return <Card className="result-card is-correct"><div className="result-symbol"><CheckCircle2 /></div><Badge tone="success">Ответ принят</Badge><h1>Спасибо, ваше мнение сохранено</h1><p>В опросе нет правильных и неправильных ответов.</p></Card>
  const correct = result?.is_correct
  return <Card className={`result-card ${correct ? 'is-correct' : 'is-wrong'}`}><div className="result-symbol">{correct ? <CheckCircle2 /> : <XCircle />}</div><Badge tone={correct ? 'success' : 'danger'}>{correct ? 'Правильно!' : 'Не в этот раз'}</Badge><h1>{correct ? (snapshot.event.event_format === 'battle' ? 'Точный ответ!' : 'Вы отлично знаете героя') : 'Зато теперь знаете больше'}</h1>{snapshot.question?.explanation && <blockquote>{snapshot.question.explanation}</blockquote>}<div className="private-stats">{snapshot.event.content_mode === 'quiz' && <div><Trophy /><span><b>{result?.rank || '—'} место</b><small>личная позиция</small></span></div>}<div><Check /><span><b>{result?.correct_count || 0} верно</b><small>за весь материал</small></span></div><div><Clock3 /><span><b>{formatTime(result?.elapsed_ms)}</b><small>ваш ответ</small></span></div></div><small className="privacy-note">{snapshot.event.content_mode === 'test' ? 'Итог теста будет показан лично вам' : 'Общую таблицу покажем только в финале'}</small></Card>
}

function PersonalFinal({ snapshot }: { snapshot: Snapshot }) {
  const result = snapshot.private_result
  if (snapshot.event.content_mode === 'survey') return <Card className="personal-final"><PartyPopper className="final-party" /><Badge tone="accent">Готово</Badge><h1>Спасибо за участие!</h1><p>Все ваши ответы на опрос сохранены.</p></Card>
  if (snapshot.event.content_mode === 'test') return <Card className="personal-final"><PartyPopper className="final-party" /><Badge tone="accent">Результат теста</Badge><h1>{result?.score_percent ?? 0}%</h1><div className="final-summary"><span><b>{result?.correct_count || 0}</b> правильных</span><i /><span><b>{result?.question_count || snapshot.session.question_count}</b> вопросов</span></div><p>Это ваш личный результат — общего рейтинга нет.</p></Card>
  return <Card className="personal-final"><PartyPopper className="final-party" /><Badge tone="accent">Финал</Badge><h1>{result?.rank === 1 ? 'Вы — победитель!' : 'Вот это была игра!'}</h1><div className="final-rank"><span>Ваше место</span><strong>{result?.rank || '—'}</strong></div><div className="final-summary"><span><b>{result?.correct_count || 0}</b> правильных</span><i /><span><b>{formatTime(result?.correct_time_ms)}</b> суммарно</span></div><p>{snapshot.event.event_format === 'battle' ? `Баттл «${snapshot.event.topic}» завершён. Спасибо за игру!` : 'Спасибо, что сделали этот вечер особенным.'}</p></Card>
}
